version: "2.4"
   
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env-local
    volumes:
      - .:/squadra_main
    ports:
      - "8000:8000"
    depends_on:
      - db