version: "3.9"
   
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env-local
    volumes:
      - .:/squadra
    ports:
      - "8000:80"
    depends_on:
      - db