# Generated by Django 3.0.7 on 2020-06-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20200615_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tekst_a',
            name='autor',
        ),
    ]
