# Generated by Django 3.1.3 on 2020-11-17 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_remove_tekst_a_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_katalogu_nadrzednego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.katalog')),
            ],
        ),
        migrations.CreateModel(
            name='Pliki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_pliku', models.CharField(max_length=6)),
                ('sciezka_do_plku', models.CharField(max_length=256)),
                ('id_katalogu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.katalog')),
            ],
        ),
    ]
