# Generated by Django 3.1.3 on 2020-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_katalog_pliki'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='nazwa',
            field=models.CharField(default='Nowy Folder', max_length=124),
        ),
    ]
