# Generated by Django 3.1.3 on 2020-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20201117_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pliki',
            name='nazwa',
            field=models.FileField(default='Nowy plik', upload_to='pliki/'),
        ),
    ]
