# Generated by Django 3.1.3 on 2020-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0011_auto_20201119_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pliki',
            name='nazwa',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pliki',
            name='sciezka',
            field=models.FileField(default='Nowy plik', upload_to='pliki/'),
        ),
    ]
