# Generated by Django 3.1.2 on 2020-11-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_auto_20200625_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='pliki/'),
        ),
    ]
