# Generated by Django 3.1.3 on 2020-11-29 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addProject', '0021_auto_20201129_1610'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('title', models.TextField(blank=True, max_length=1024, null=True)),
                ('creation_time', models.DateTimeField()),
                ('modification_timee', models.DateTimeField()),
                ('id_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_requests_creator', to=settings.AUTH_USER_MODEL)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addProject.project')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_requests_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
