# Generated by Django 3.1.4 on 2021-01-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_board_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='prioryty',
            field=models.CharField(blank=True, choices=[('niski', 'niski'), ('sredni', 'sredni'), ('wysoki', 'wysoki')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
