# Generated by Django 3.0.7 on 2020-06-15 12:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tekst_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text_app', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('autor', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
