# Generated by Django 3.1.2 on 2020-11-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_app', '0003_remove_tekst_a_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tekst_a',
            name='title',
        ),
    ]
