# Generated by Django 3.1.3 on 2020-11-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_app', '0010_auto_20201119_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pliki',
            name='id_katalogu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='squadra_app.katalog'),
        ),
    ]
