# Generated by Django 3.1.2 on 2020-11-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='displayusername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_projektu', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectCreate',
        ),
    ]
