# Generated by Django 3.1.2 on 2020-11-14 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addProject', '0004_auto_20201114_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapp',
            name='tworcaProjektu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
