# Generated by Django 3.1.2 on 2020-11-14 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addProject', '0005_auto_20201114_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectapp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_projektu', models.CharField(max_length=30)),
                ('rola', models.CharField(blank=True, choices=[('Moderator', 'Moderator'), ('Menager', 'Menager'), ('User', 'User'), ('Person', 'Person')], max_length=30, null=True)),
                ('tworcaProjektu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Projectapp',
        ),
    ]
