# Generated by Django 3.1.2 on 2020-11-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProject', '0006_auto_20201114_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_projektu', models.CharField(max_length=30)),
                ('tworcaProjektu', models.CharField(max_length=20)),
                ('rola', models.CharField(blank=True, choices=[('Moderator', 'Moderator'), ('Menager', 'Menager'), ('User', 'User'), ('Person', 'Person')], max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Projectapp1',
        ),
    ]
