# Generated by Django 3.1.2 on 2020-11-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addProject', '0009_new_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectapp',
            old_name='tworcaProjektu_id',
            new_name='uzytkownik_id',
        ),
    ]
