# Generated by Django 3.1.2 on 2020-11-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProject', '0013_auto_20201114_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapp',
            name='nazwa_projektu',
            field=models.CharField(max_length=30),
        ),
    ]
