# Generated by Django 3.1.2 on 2020-11-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addProject', '0014_auto_20201114_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapp',
            name='nazwa_projektu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addProject.new_project'),
        ),
    ]
