# Generated by Django 3.1.2 on 2020-11-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addProject', '0015_auto_20201114_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_project',
            name='project_user_cr',
        ),
    ]
