# Generated by Django 3.1.2 on 2020-11-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProject', '0019_auto_20201114_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapp',
            name='tworcaProjektu_id',
            field=models.CharField(default='11', max_length=30),
            preserve_default=False,
        ),
    ]
