# Generated by Django 3.1.3 on 2021-01-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProject', '0021_auto_20201129_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2011-09-01T13:20:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
